### ISSUE TITLE
Novel download scrambles text.

### ISSUE THREAD

**Issue by GamerAmogusb** [Tenpi/Pixiv-Downloader#1]
Been having an issue where the japanese text in the download gets scrambled when downloading from tags. The first few novels download fine but after about 20 they start to become scrambled.

**Comment by GamerAmogusb** [comment]
It seems to happen >24 downloaded novels which is the amount displayed on a single page

**Comment by Moebytes** [comment]
Explain what you mean by "scrambled". You probably just have to read it from right to left instead of left to right. You can probably find some tool online to reverse the text for you if you want to read from left to right.

**Comment by GamerAmogusb** [comment]
The entire text file looks like this: "ÿØÿà JFIF      ÿÛ C 


		
%# , #&')*)-0-(0%()(ÿÛ C



(((((((((((((((((((((((((((((((((((((((((((((((((((ÿÀ R ð ÿÄ              ÿÄ J 	   !12AQRq"3a‘4Vr¤ÓB’#¡$S‚ÁCbd±³%csu“¢²ÑÿÄ            ÿÄ &       1S¢Ò!2AQ"aÿÚ   ? ú¦7§ÌŸ­,XoO™?ZX°ÞŸ2~´±a½>dýibÃz|ÉúÒÅ†ôù“õ¥‹
éó'ëKÓæOÖ–,7§ÌŸ­,X$œ­,9œP&äø­Ò7'Ä}hZFäø­Ir1žê!7§ÌŸ­,XoO™?ZX°ÞŸ2~´±a½>dýibÃz|ÉúÒÅ†ôù“õ¥‹
éó'ëKÓæOÖ–,7§ÌŸ­,XoO™?ZX°ÞŸ2~´±a½>dýibÄÞŸ2~´±gT»GÖ½Nã(P 1@b€ÅŠb}å¿ZÍx”«	ó»(õ®4Ê%twåýÌþOúW8ý<“úTb½£(P 1@b€ÅŠ(P!åT^7ðÓè+Ë9p—UíZõ;’€ (
€ (
b}å¿ZÍxJ°Ÿ7²ZãAÑÌ¢WGq@PN_ÜÏäÿ ¥sÓÉ?¥EzE@P@P@P•ã
>‚¼Ó—	-AF{GÖ½Nä (
€ (
ØŸyoÖ³^%*Â|îHõ®4Ê%twåýÌþOúW8ý<“úTW¡ÔP@P@P yP^7ðÓè+Í9p’Ôg´}kÔîv'	¬×„«	ˆ
RAÜî×9³œºØ¯0þÚ^Šóí¥à¸Ø¯0þÚ^Šóí¥à¸Ø¯0þÚ^Šóí¥à¹P•nðþÚ“0;ZWÃ+ÛY‹.v«Ì?¶­Öãj¼Ãûirãj¼ÃûirîÊW³¶1-O«³ý3±^aýµ»ÂÜ»æÛKÁq±^aý´¼æÛKÁq±^aý´¼æÛKÁq±^aý´¼æÛKÁq±^aý´¼æÛKÁr)*	'pà3Ù§Ð‡3ãÊ+¥nœ<«M/øiôæœ¸Ij
3Ú>µêw;ï¬×†jÂs_	>•ÊrÄåÝD@P
ŽÐ¤‡ÝRqEg±ý(ŸÓUA@P@PAÊû"

**Comment by Moebytes** [comment]
Can you post the link to this novel, it seems like it is downloading an illustration. That's a binary image file.

**Comment by GamerAmogusb** [comment]
Ok a few things
1: it is downloading from novels somewhat?
2: When trying to click on the link inside pixiv downloader, it takes me to the wrong url, for instance this url is the correct one: "https://www.pixiv.net/novel/show.php?id=5781" but this is where the app sends me: "https://www.pixiv.net/en/artworks/5781" However this is also true of novels it successfully downloaded with normal text.
3: You're correct that it's downloading an illustration, if I change the extension of the garbled files to .png I get the album cover. 
![迷い込んだ小さな果実](https://user-images.githubusercontent.com/115679221/196016108-3850ad9a-6bd7-4d57-a81f-e180cd0a7f12.png) so for some reason after it downloads a certain number of novels it seems to start downloading the album cover?

**Comment by Moebytes** [comment]
You can just delete those files if you want, it is just downloading the cover after downloading the novel (but incorrectly as also a TXT file), I will change it when I have time.

**Comment by GamerAmogusb** [comment]
On my end, it's only downloading the cover, and not the novel meaning that all I have is the scrambled text
