### ISSUE TITLE
App seems to not work.

### ISSUE THREAD

**Issue by FunctionalFalcon** [Tenpi/Pixiv-Downloader#2]
![ảnh](https://github.com/user-attachments/assets/409202f4-65cf-440f-904b-847625e1c166)

App seems to not work. Maybe because i completely deleted Microsoft Edge from laptop? I have firefox and it doesnt seeems to work with firefox.

**Comment by FunctionalFalcon** [comment]
issue happens when i try to login through the browser

**Comment by Moebytes** [comment]
Hello, yes it stopped working. Please update to 0.1.7, it should be fixed
